name: 'deploy ecs task'
description: 'deploy the task to ecs cluster, note that the service name should be identical to the repository name'
inputs:
  task-definition:
    description: >
      The definition of the task, which will be deployed to ecs cluster
    required: true
  cluster:
    description: >
      The name of the ecs cluster, to which the task will be deployed
    required: true
  config-path:
    description: >-
      path to the config file in json format
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: load variables
      id: load-vars
      uses: myriad-actions/load-variables@v1
      with:
        config-path: ${{ inputs.config-path }}
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ fromJson(steps.load-vars.outputs.vars).role-to-assume }}
        aws-region: ${{ fromJson(steps.load-vars.outputs.vars).aws-region }}
    - name: Download task definition
      run: 
        aws ecs describe-task-definition --task-definition ${{ inputs.task-definition }} --query taskDefinition > ecs-task-def.json
      shell: bash
    - name: Deploy Amazon ECS task by definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        service: ${{ github.event.repository.name }}
        cluster: ${{ inputs.cluster }}
        wait-for-service-stability: true
        force-new-deployment: true
